### ISSUE TITLE
Improve Media Handling

### ISSUE THREAD

**Issue by zweishar** [CityOfBoston/boston.gov-d8#210]
# Desired Functionality

- Unified UI for uploading media (in D7 there are at least 2 different UI's that do essentially the same thing)
- Automatically organize file uploads so they're no all in root file directory (which slows down the process for content authors a lot right now)
- A system that makes re-use and searching for media easier (media library)
- Ability to re-name files through the UI (so that finding them later is easier)
- Easily link to documents + other pages in WYSIWYG
- Easily embed images in the WYSIWYG with ability to control alignment, size, etc

# Options
- Stick with standard file fields + IMCE (what we currently have)
- Move towards media entities (new to D8)

# Why we should use Media
- If we stick with standard file fields + IMCE, we won't be able to improve the editing experience beyond what we currently have in D7. Media entities give us more control + flexibility as developers.
- Media entities make content more future proof, especially when dealing with WYSIWYG. Currently, if you embed a file into the WYSIWYG and then delete / change that file, you need to go back to every page you used that file on and change it. When embedding a media entity, you can change the file out and it will automatically update in every place that media entity was used.
- By using media everywhere, we can ensure a consistent experience for editors.
- Media allows non-technical folks to directly manipulate the file system. That's not a task that content authors should have to worry about. It also leads to the problems that we currently have with a disorganized file system.

# Challenges
- The migration complexity will be increased. In order to provide a consistent editing experience, we should change every file field over to media. There is a contrib module that looks like it may do most of the heavy lifting for us, but it will still increase the overall time the migration takes.
- There isn't currently a way to launch a media creation modal directly from Linkit, but there is a way to launch CKeditor. This means that creating + linking to a file in the WYSIWYG is currently a 2 part process (upload the document, then launch linkit). We can likely cut that down to 1 step, but it may require some custom work (chance to contribute back to the community).
- Media is new to D8, so we're more likely to encounter bugs. That said the community support for media is very strong so I'm confident we can address anything that comes up.

# Info on current state
- Nearly all content editors besides James use the WYSIWIG editor to upload documents
- Most uploads are documents, not images (really relevant for public notices)

**Comment by zweishar** [comment]
**Notes**
- At `admin/config/media/imce/admin` we can configure behavior for what happens when uploading a duplicate file (aka same name). Currently, content admins upload many versions of one file, all of which get saved on the server. Instead, we can choose "Replace the existing file with the new one", which will prevent this issue from occuring

**Comment by zweishar** [comment]
In order to stay unified, we should choose either IMCE or Media, but not both.

**IMCE**
Pros
- Will be familiar to content authors from D7 site
- Highly stable (both library itself and Drupal's integration with it)
Cons
- Difficult to find things
- Unstructured managment of the filesystem will lead to messy file system over time (no means of structural enforcement)

**Media**
Pros
- Highly structured file managment
- Flexible for developers
- Allows for centralized place to manage media. Change it once and it's updated everywhere

Cons
- More complicated to implement + manage
- Very new to Drupal 8, which means we're more likely to encounter bugs
- No built in way to create media from linkit

**Comment by davidrkupton** [comment]
I quite like the idea of the media.
I agree it may potentially be buggy, but the unstructured file system is a big bugbear for us. Also I don't expect we will be using many "Edge" features. 
To my mind the big con is linkit. Can linkit be used in any way with media or is it imce-only?
Does the media module have any ability to search like linkit?

**Comment by jimafisk** [comment]
Possibly worth a look: https://www.drupal.org/project/linkit_media_file_direct

**Comment by zweishar** [comment]
Another thing to consider here is consistency and how that could affect the complexity of the migration. If we want to go down the media route, and we want to provide a consistent interface for uploading media, we will need to account for this in the migration. All file / image fields will need to be changed over to media fields, and we will need to write more custom code to string the migration together as the auto-generated migration files aren't likely to work.

**Comment by zweishar** [comment]
Jim found https://www.drupal.org/project/migrate_file_to_media which may reduce the complexity on the migration end.

**Comment by zweishar** [comment]
Development team came to a consensus that using media module is preferable to IMCE. Reasons being:
- We will never be able to improve the editing experience with IMCE. It will be the same as D7. We should take advantage of new functionality in D8.
- The migration complexity may be mitigated by the contrib module linked above. But regardless we're going to have to re-write file paths between D7 + D8 to cut down on the number of files in the root public file directory, so migrating to media shouldn't be _too much_ more work

**Comment by zweishar** [comment]
Lightning has broken out it's functionality into sub-modules, so we can isntall the `lightning_media` without installing the profile.

An option that might be better is to use https://www.drupal.org/project/media_entity_browser for WYSIWYG embeds and core's new "Media Library" field widget for image / document fields.

**Comment by zweishar** [comment]
**Implementation Steps**
- [ ] `composer require drupal/linkit:5.x-dev`
- [ ] Uninstall / reinstsall media module (to get the default media configs back)
- [ ] Set up 2 matchers in Linkit
    - [ ] One for nodes
    - [ ] One for media of type document. Be sure to use "Direct URL to Media File Entity"
- [ ] Set up text formats to use linkit (be sure to add `data-entity-substitution` as an allowed property on a)
- [ ] Install core's `media_library` experimental module
- [ ] Convert all existing file / image fields to media fields (use https://www.drupal.org/project/migrate_file_to_media if possible)
- [ ] Set up https://www.drupal.org/project/migrate_file_to_media for embedding media into WYSIWYG
    - [ ] Try to use the view provided by `media_library` so that interface is the same for WYSIWYG + regular field uploads
    - [ ] Pay attention to options for alignment, image styles etc and ensure that all options work and are intuitive (ex. we likely don't want to provide every possible image style as an option, but should use something simple like small, medium, large)

**Comment by zweishar** [comment]
- Lock content editors from editing existing images
- Skip place button

**Comment by zweishar** [comment]
**Questions**
- [ ] Do we want to limit the WYSIWYG embedding to images only? (embedding a document seems like something we'll never do)

**Todo**
- [ ] If we're allowing file embeds, I need to fix `BosMediaImage` as it's currently beings used for files too (which it doesn't work for)
- [ ] Closely review everything added by `lightning_media` and disable / remove anything we're not using

**Comment by reillyzlab** [comment]
Grooming as of 1/8/19:

Roles:
TBD

On Media 
- Not accessible through WYSIWIG


On LinkIt
- [ ] Create document uploading option on LinkIt [new feature we'd need to create]
- [ ] Submit document uploading to the Drupal community


Current state: 
- Nearly all content editors besides James use the WYSIWIG editor to upload documents
- Most uploads are documents, not images (really relevant for public notices)

-

**Comment by reillyzlab** [comment]
# Possible further enhancements (track all)
Groom at Tuesday stand up before implementing any of these.

- [ ] Add ability for content authors to crop images during the upload process
- [ ] Add ability to upload multiple files at once
- [ ] Drag and drop files onto upload widget to start upload
- [ ] Integrate [blazy](https://www.drupal.org/project/blazy) for lazy loaded images
- [ ] Use responsive image styles to improve mobile performance
- [ ] Potentially collapse photo component, charting (component? - future state), linkit, and media to get a truly seamless experience
