### ISSUE TITLE
Remove unused components

### ISSUE THREAD

**Issue by zweishar** [CityOfBoston/boston.gov-d8#230]
## Components with documented issues
- [x] `tabbed_content_tab`: #76 (paragraph)
- [x] `script_embed`: #69 (paragraph)
- [x] `status_override`: #75 (paragraph)
- [x] `tabbed_content` #76 (content type)

## Components without documented issues (taken from board)
- [x] `map_coordinates` (paragraph)
- [x] `map_esri_feed` (paragraph)
- [x] `map_pin` (paragraph)
- [x] `maps_basemap` (taxonomy)
- [x] `maps_esri_feed` (taxonomy)
- [x] `featured_item` (paragraph)
- [x] `recollect_widget` (paragarph)
- [x] `user_action` (paragraph)
